## Search with Options

- Piece or Corpus
- Actual or Incremental Durations
- Chromatic or Diatonic
- Exact or Close
- Classify

***

### Load Crim Intervals and Pandas

In [4]:
from crim_intervals import *
import pandas as pd
import ast
import matplotlib
from itertools import tee, combinations

def pairwise(iterable):
    "s -> (s0,s1), (s1,s2), (s2, s3), ..."
    a, b = tee(iterable)
    next(b, None)
    return zip(a, b)

def get_ratios(input_list):
    ratio_pairs = []
    for a, b in pairwise(input_list):
        ratio_pairs.append(b / a)
    return ratio_pairs

def compare_ratios(ratios_1, ratios_2):
    
    ## division of lists 
    # using zip() + list comprehension 
    diffs = [i - j for i, j in zip(ratios_1, ratios_2)] 
    abs_diffs = [abs(ele) for ele in diffs] 
    sum_diffs = sum(abs_diffs)

    return sum_diffs

#results["Pattern_Generating_Match"] = results["Pattern_Generating_Match"].apply(tuple) 

def get_ratio_distances(results, pattern_col, output_cols):
    
    matches = []

    for name, group in results.groupby(pattern_col):

        ratio_pairs = list(combinations(group.index.values, 2))

        for a, b in ratio_pairs:
            
            a_match = results.loc[a]
            b_match = results.loc[b]
            
            sum_diffs = compare_ratios(a_match.duration_ratios, b_match.duration_ratios)
            
            match_dict = {
                "pattern": name,
                "sum_diffs": sum_diffs
            }
            
            for col in output_cols:
                match_dict.update({
                    f"match_1_{col}": a_match[col],
                    f"match_2_{col}": b_match[col]
                })
                
            matches.append(match_dict)
            
    return pd.DataFrame(matches)

def get_mei(WorkList_mei):

    corpus = CorpusBase(WorkList_mei)
    
# correct path

    WorkList_mei = [el.replace("CRIM_", "https://crimproject.org/mei/MEI_4.0/CRIM_") for el in WorkList_mei]

# Correct the MEI metadata

    import xml.etree.ElementTree as ET
    import requests

    MEINSURI = 'http://www.music-encoding.org/ns/mei'
    MEINS = '{%s}' % MEINSURI

    for i, path in enumerate(WorkList_mei):
        
        try:
            if path[0] == '/':
                mei_doc = ET.parse(path)
            else:
                mei_doc = ET.fromstring(requests.get(path).text)

          # Find the title from the MEI file and update the Music21 Score metadata
            title = mei_doc.find('mei:meiHead//mei:titleStmt/mei:title', namespaces={"mei": MEINSURI}).text
            print(path, title)
            corpus.scores[i].metadata.title = title
        except:
            continue
    return corpus

# def get_ema_for_observation_id(obs_id):
#     # get Obs_1_ema
#     my_ema_mei_dictionary = dict()
#     url = "https://crimproject.org/data/observations/{}/".format(obs_id)
#     response = requests.get(url)
#     Obs_json = response.json()
    
#     # Obs_ema = Obs_json["ema"]
    
#     my_ema_mei_dictionary["id"]=Obs_json["id"]
#     my_ema_mei_dictionary["musical type"]=Obs_json["musical_type"]
#     my_ema_mei_dictionary["int"]=Obs_json["mt_fg_int"]
#     my_ema_mei_dictionary["tint"]=Obs_json["mt_fg_tint"]
#     my_ema_mei_dictionary["ema"]=Obs_json["ema"]
#     my_ema_mei_dictionary["mei"]=Obs_json["piece"]["mei_links"][0]
#     my_ema_mei_dictionary["pdf"]=Obs_json["piece"]["pdf_links"][0]
   
    
#     # Obs_piece = Obs_json["piece"]
#     # Obs_mei = Obs_piece["mei_links"]
    
#     print(f'Got: {obs_id}')
    
#     # return {"ema":Obs_ema,"mei":Obs_mei}
    
#     return my_ema_mei_dictionary

### The Complete Corpus

In [ ]:
work_list = ['CRIM_Mass_0001_1.mei',
 'CRIM_Mass_0001_2.mei',
 'CRIM_Mass_0001_3.mei',
 'CRIM_Mass_0001_4.mei',
 'CRIM_Mass_0001_5.mei',
 'CRIM_Mass_0002_1.mei',
 'CRIM_Mass_0002_2.mei',
 'CRIM_Mass_0002_3.mei',
 'CRIM_Mass_0002_4.mei',
 'CRIM_Mass_0002_5.mei',
 'CRIM_Mass_0003_1.mei',
 'CRIM_Mass_0003_2.mei',
 'CRIM_Mass_0003_3.mei',
 'CRIM_Mass_0003_4.mei',
 'CRIM_Mass_0003_5.mei',
 'CRIM_Mass_0004_1.mei',
 'CRIM_Mass_0004_2.mei',
 'CRIM_Mass_0004_3.mei',
 'CRIM_Mass_0004_4.mei',
 'CRIM_Mass_0004_5.mei',
 'CRIM_Mass_0005_1.mei',
 'CRIM_Mass_0005_2.mei',
 'CRIM_Mass_0005_3.mei',
 'CRIM_Mass_0005_4.mei',
 'CRIM_Mass_0005_5.mei',
 'CRIM_Mass_0006_1.mei',
 'CRIM_Mass_0006_2.mei',
 'CRIM_Mass_0006_3.mei',
 'CRIM_Mass_0006_4.mei',
 'CRIM_Mass_0006_5.mei',
 'CRIM_Mass_0007_1.mei',
 'CRIM_Mass_0007_2.mei',
 'CRIM_Mass_0007_3.mei',
 'CRIM_Mass_0007_4.mei',
 'CRIM_Mass_0007_5.mei',
 'CRIM_Mass_0008_1.mei',
 'CRIM_Mass_0008_2.mei',
 'CRIM_Mass_0008_3.mei',
 'CRIM_Mass_0008_4.mei',
 'CRIM_Mass_0008_5.mei',
 'CRIM_Mass_0009_1.mei',
 'CRIM_Mass_0009_2.mei',
 'CRIM_Mass_0009_3.mei',
 'CRIM_Mass_0009_4.mei',
 'CRIM_Mass_0009_5.mei',
 'CRIM_Mass_0010_1.mei',
 'CRIM_Mass_0010_2.mei',
 'CRIM_Mass_0010_3.mei',
 'CRIM_Mass_0010_4.mei',
 'CRIM_Mass_0010_5.mei',
 'CRIM_Mass_0011_1.mei',
 'CRIM_Mass_0011_2.mei',
 'CRIM_Mass_0011_3.mei',
 'CRIM_Mass_0011_4.mei',
 'CRIM_Mass_0011_5.mei',
 'CRIM_Mass_0012_1.mei',
 'CRIM_Mass_0012_2.mei',
 'CRIM_Mass_0012_3.mei',
 'CRIM_Mass_0012_4.mei',
 'CRIM_Mass_0012_5.mei',
 'CRIM_Mass_0013_1.mei',
 'CRIM_Mass_0013_2.mei',
 'CRIM_Mass_0013_3.mei',
 'CRIM_Mass_0013_4.mei',
 'CRIM_Mass_0013_5.mei',
 'CRIM_Mass_0014_1.mei',
 'CRIM_Mass_0014_2.mei',
 'CRIM_Mass_0014_3.mei',
 'CRIM_Mass_0014_4.mei',
 'CRIM_Mass_0014_5.mei',
 'CRIM_Mass_0015_1.mei',
 'CRIM_Mass_0015_2.mei',
 'CRIM_Mass_0015_3.mei',
 'CRIM_Mass_0015_4.mei',
 'CRIM_Mass_0015_5.mei',
 'CRIM_Mass_0016_1.mei',
 'CRIM_Mass_0016_2.mei',
 'CRIM_Mass_0016_3.mei',
 'CRIM_Mass_0016_4.mei',
 'CRIM_Mass_0016_5.mei',
 'CRIM_Mass_0017_1.mei',
 'CRIM_Mass_0017_2.mei',
 'CRIM_Mass_0017_3.mei',
 'CRIM_Mass_0017_4.mei',
 'CRIM_Mass_0017_5.mei',
 'CRIM_Mass_0018_1.mei',
 'CRIM_Mass_0018_2.mei',
 'CRIM_Mass_0018_3.mei',
 'CRIM_Mass_0018_4.mei',
 'CRIM_Mass_0018_5.mei',
 'CRIM_Mass_0019_1.mei',
 'CRIM_Mass_0019_2.mei',
 'CRIM_Mass_0019_3.mei',
 'CRIM_Mass_0019_4.mei',
 'CRIM_Mass_0019_5.mei',
 'CRIM_Mass_0020_1.mei',
 'CRIM_Mass_0020_2.mei',
 'CRIM_Mass_0020_3.mei',
 'CRIM_Mass_0020_4.mei',
 'CRIM_Mass_0020_5.mei',
 'CRIM_Mass_0021_1.mei',
 'CRIM_Mass_0021_2.mei',
 'CRIM_Mass_0021_3.mei',
 'CRIM_Mass_0021_4.mei',
 'CRIM_Mass_0021_5.mei',
 'CRIM_Mass_0022_2.mei',
 'CRIM_Model_0001.mei',
 'CRIM_Model_0008.mei',
 'CRIM_Model_0009.mei',
 'CRIM_Model_0010.mei',
 'CRIM_Model_0011.mei',
 'CRIM_Model_0012.mei',
 'CRIM_Model_0013.mei',
 'CRIM_Model_0014.mei',
 'CRIM_Model_0015.mei',
 'CRIM_Model_0016.mei',
 'CRIM_Model_0017.mei',
 'CRIM_Model_0019.mei',
 'CRIM_Model_0020.mei',
 'CRIM_Model_0021.mei',
 'CRIM_Model_0023.mei',
 'CRIM_Model_0025.mei',
 'CRIM_Model_0026.mei',
]

### Sample Pair of Mass+Model

In [5]:
WorkList_mei = ['CRIM_Mass_0005_1.mei',
 'CRIM_Mass_0005_2.mei',
 'CRIM_Mass_0005_3.mei',
 'CRIM_Mass_0005_4.mei',
 'CRIM_Mass_0005_5.mei',
'CRIM_Model_0008.mei']


get_mei(WorkList_mei)

# work_list = [
# 'CRIM_Model_0008.mei']

# work_list = [el.replace("CRIM_", "https://crimproject.org/mei/MEI_4.0/CRIM_") for el in work_list]
# corpus = CorpusBase(work_list)

# import xml.etree.ElementTree as ET
# import requests

# MEINSURI = 'http://www.music-encoding.org/ns/mei'
# MEINS = '{%s}' % MEINSURI

# for i, path in enumerate(work_list):
    
#     try:
#         if path[0] == '/':
#             mei_doc = ET.parse(path)
#         else:
#             mei_doc = ET.fromstring(requests.get(path).text)

#       # Find the title from the MEI file and update the Music21 Score metadata
#         title = mei_doc.find('mei:meiHead//mei:titleStmt/mei:title', namespaces={"mei": MEINSURI}).text
#         print(path, title)
#         corpus.scores[i].metadata.title = title
#     except:
#         continue

Requesting file from CRIM_Mass_0005_1.mei...
Import from CRIM_Mass_0005_1.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...
Requesting file from CRIM_Mass_0005_2.mei...
Import from CRIM_Mass_0005_2.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...
Requesting file from CRIM_Mass_0005_3.mei...
Import from CRIM_Mass_0005_3.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...
Requesting file from CRIM_Mass_0005_4.mei...
Import from CRIM_Mass_0005_4.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...
Requesting file from CRIM_Mass_0005_5.mei...
Import from CRIM_Mass_0005_5.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...
Requesting file from CRIM_Model_0008.mei...
Import from CRIM_Model_0008.mei failed, please check your url. File paths must begin with a '/'. Continuing to next file...

Exception: At least one score must be succesfully imported

In [60]:
vectors = IntervalBase(corpus.note_list)
patterns = into_patterns([vectors.generic_intervals], 5)
close_matches = find_close_matches(patterns, 3, 0)
output_close = export_pandas(close_matches)
output_close["pattern_generating_match"] = output_close["pattern_generating_match"].apply(tuple)
results = pd.DataFrame(output_close)
results["duration_ratios"] = results.note_durations.apply(get_ratios)
ratio_distances = get_ratio_distances(results, "pattern_generating_match", ["piece_title", "part", "start_measure", "end_measure"])
ratios_filtered = ratio_distances[ratio_distances.sum_diffs <= 1]
ratios_filtered.head()

Finding close matches...
260 melodic intervals had more than 3 exact or close matches.

,pattern,sum_diffs,match_1_piece_title,match_2_piece_title,match_1_part,match_2_part,match_1_start_measure,match_2_start_measure,match_1_end_measure,match_2_end_measure
0,"(-5, 2, 2, -2, -2)",0.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Sup[erius],Sup[erius],84,91,85,92
6,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Altus,Tenor,239,182,239,182
15,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Sanctus,Sup[erius],Bassus,132,32,133,33
16,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Agnus Dei,Sup[erius],Sup[erius],132,85,133,86
18,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Agnus Dei,Bassus,Sup[erius],32,85,33,86

In [61]:
len(ratios_filtered)

8170

In [66]:
ratios_filtered['pattern'].nunique()

250

In [63]:
df = ratios_filtered.sort_values(['match_1_piece_title', 'match_1_start_measure'])

df.head(40)

,pattern,sum_diffs,match_1_piece_title,match_2_piece_title,match_1_part,match_2_part,match_1_start_measure,match_2_start_measure,match_1_end_measure,match_2_end_measure
56341,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,[Superius],Altus,1,3,4,6
56342,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,1,5,4,8
56343,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,[Superius],Bassus,1,7,4,10
56347,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,Altus,Tenor,3,5,6,8
56348,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,Altus,Bassus,3,7,6,10
56349,"(4, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,Tenor,Bassus,5,7,8,10
12150,"(-2, -2, -2, 2, -2)",0.916667,Ave Maria,Ave Maria,[Superius],Altus,8,10,10,12
12151,"(-2, -2, -2, 2, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,8,12,10,14
16882,"(-2, -2, 2, -2, 4)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,8,12,10,14
22805,"(-2, 2, -2, 4, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,9,13,11,15
40207,"(2, -2, 4, -2, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,9,13,11,15
12153,"(-2, -2, -2, 2, -2)",0.916667,Ave Maria,Ave Maria,Altus,Tenor,10,12,12,14
25602,"(-2, 4, -2, -2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,10,14,11,15
56013,"(4, -2, -2, 2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,10,14,12,16
26333,"(1, 1, 2, 2, -3)",0.250000,Ave Maria,Ave Maria,[Superius],Tenor,16,20,19,23
26336,"(1, 1, 2, 2, -3)",0.000000,Ave Maria,Ave Maria,Altus,Bassus,18,22,21,25
40281,"(2, 1, 2, -2, -2)",0.000000,Ave Maria,Ave Maria,Altus,Bassus,32,36,34,38
46556,"(2, 2, 1, 2, -2)",0.666667,Ave Maria,Ave Maria,[Superius],Altus,32,32,34,34
46559,"(2, 2, 1, 2, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,32,36,34,38
46560,"(2, 2, 1, 2, -2)",0.666667,Ave Maria,Ave Maria,[Superius],Bassus,32,36,34,38
46563,"(2, 2, 1, 2, -2)",0.666667,Ave Maria,Ave Maria,Altus,Tenor,32,36,34,38
46564,"(2, 2, 1, 2, -2)",0.000000,Ave Maria,Ave Maria,Altus,Bassus,32,36,34,38
26903,"(1, 2, -2, -2, -2)",0.000000,Ave Maria,Ave Maria,Altus,Bassus,33,37,35,39
26954,"(1, 2, -2, 1, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Altus,33,79,34,80
26955,"(1, 2, -2, 1, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,33,37,34,38
26956,"(1, 2, -2, 1, -2)",0.000000,Ave Maria,Ave Maria,[Superius],Bassus,33,82,34,83
39595,"(2, -2, 1, -2, 2)",1.000000,Ave Maria,Ave Maria,[Superius],Altus,33,37,35,39
39596,"(2, -2, 1, -2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Altus,33,79,35,81
39597,"(2, -2, 1, -2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Altus,33,139,35,141
39598,"(2, -2, 1, -2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Tenor,33,37,35,39
39599,"(2, -2, 1, -2, 2)",0.000000,Ave Maria,Ave Maria,[Superius],Bassus,33,82,35,84
46570,"(2, 2, 1, 2, -2)",0.666667,Ave Maria,Ave Maria,Tenor,Bassus,36,36,38,38
26959,"(1, 2, -2, 1, -2)",0.000000,Ave Maria,Ave Maria,Tenor,Bassus,37,82,38,83
39600,"(2, -2, 1, -2, 2)",1.000000,Ave Maria,Ave Maria,Altus,Altus,37,79,39,81
39601,"(2, -2, 1, -2, 2)",1.000000,Ave Maria,Ave Maria,Altus,Altus,37,139,39,141
39602,"(2, -2, 1, -2, 2)",1.000000,Ave Maria,Ave Maria,Altus,Tenor,37,37,39,39
39603,"(2, -2, 1, -2, 2)",1.000000,Ave Maria,Ave Maria,Altus,Bassus,37,82,39,84
39609,"(2, -2, 1, -2, 2)",0.000000,Ave Maria,Ave Maria,Tenor,Bassus,37,82,39,84
26199,"(1, 1, 2, -2, -2)",1.000000,Ave Maria,Ave Maria,[Superius],Altus,40,94,43,95
26200,"(1, 1, 2, -2, -2)",1.000000,Ave Maria,Ave Maria,[Superius],Altus,40,98,43,99

In [65]:
grouped = ratios_filtered.groupby(by='pattern')
grouped.head(40)

,pattern,sum_diffs,match_1_piece_title,match_2_piece_title,match_1_part,match_2_part,match_1_start_measure,match_2_start_measure,match_1_end_measure,match_2_end_measure
0,"(-5, 2, 2, -2, -2)",0.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Sup[erius],Sup[erius],84,91,85,92
6,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Altus,Tenor,239,182,239,182
15,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Sanctus,Sup[erius],Bassus,132,32,133,33
16,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Agnus Dei,Sup[erius],Sup[erius],132,85,133,86
18,"(-5, 2, 2, 2, 2)",0.0,Missa Ave Maria: Sanctus,Missa Ave Maria: Agnus Dei,Bassus,Sup[erius],32,85,33,86
...,...,...,...,...,...,...,...,...,...,...
56614,"(8, -2, -2, -2, -2)",1.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Altus,Bassus,267,267,269,269
56616,"(8, -2, -2, -2, -2)",0.0,Missa Ave Maria: Credo,Ave Maria,Altus,Tenor,267,27,269,28
56623,"(8, -2, -2, -2, -2)",1.0,Missa Ave Maria: Credo,Missa Ave Maria: Credo,Bassus,Bassus,265,267,266,269
56625,"(8, -2, -2, -2, -2)",0.0,Missa Ave Maria: Credo,Ave Maria,Bassus,Tenor,265,27,266,28
56628,"(8, -2, -2, -2, -2)",1.0,Missa Ave Maria: Credo,Ave Maria,Bassus,Tenor,267,27,269,28

In [58]:
pattern_counts = pd.DataFrame(ratios_filtered["pattern"].value_counts())
pattern_counts

                     pattern
(-2, -2, -2, 2, -2)     1119
(-2, -2, -2, 3, -2)     1102
(3, -2, -2, -2, 2)       926
(-2, -2, -2, 2, -3)      915
(2, 2, -2, -2, -2)       869
...                      ...
(-2, -3, 5, -2, -2)        1
(1, -2, 2, 1, 2)           1
(-2, 2, 5, -2, -2)         1
(-4, 1, 2, 2, 2)           1
(-2, -2, 3, 1, -2)         1

[697 rows x 1 columns]

In [51]:
ratios_filtered.drop_duplicates(['pattern']).to_csv('test3.csv')

In [64]:
ratios_filtered.to_csv("Mod_8_Mass_5_V5_M3_C0_D1.csv")
#Mod_1_Mass_2_V5_M3_C1_D2_F2

### Classifier and Output